#! /usr/bin/env python
# -*- coding: utf-8 -*-


cand_fus_prov = {'PSOE': ['PSE-EE (PSOE)', "PSOE", "PSC", "PSE-EE", "PSdeG-PSOE", "PSC-PSOE", "PSOE-NCa"],
                 "PODEMOS": ["PODEMOS-AHAL DUGU", "PODEMOS", "PODEMOS-COMPROMÍS", "PODEMOS-En Marea-ANOVA-EU", "PODEMOS-Ahora Alto Aragón en Común", "PODEMOS - COMPROMIS", "PODEMOS-EN MAREA-ANOVA-EU", "EN COMÚ"],
                 'EH Bildu': ['EH Bildu'],
                 'UPYD': ['UPYD'],
                 "C's": ["C's", "C´s"],
                 "PP": ["PP-PAR", "PP", "PP-FORO", "UPN-PP"],
                 "EAJ-PNV": ["EAJ-PNV"],
                 "PACMA": ["PACMA"],
                 "IU": ["IU-UPeC", "UNIDAD POPULAR", "UPeC-IU-IZCA", "IU-UpeC", "IUC-UPeC", "IU-B-UPeC", "IU-CHA-UPeC", "UP-UPeC", "EUPV-UPeC", "UPeC-IU", "IULV-CA, UPeC", "IULV-CA,UPeC", "IU-UPeC-IAS", "UP: IULV-CA, UPeC", "UPB: IU-UPeC"],
                 "RECORTES CERO-GRUPO VERDE": ["RECORTES CERO-GRUPO VERDE"],
                 "CANARIAS DECIDE": ["CANARIAS DECIDE"],
                 "PCPE": ["PCPE"],
                 "Unió": ["Unio.Cat", "unio.cat"],
                 "VOX": ["VOX"],
                 "ERC": ["ERC-CATSI", "ERC-CATSÍ"],
                 "+MAS+": ["+MAS+"],
                 "Independientes-FIA": ["Independientes-FIA"],
                 "FE de las JONS": ["FE de las JONS"],
                 "PH": ["PH"],
                 "OE": ["OE"],
                 "Ln": ["Ln"],
                 "CENTRO MODERADO": ["CENTRO MODERADO"],
                 "P-LIB": ["P-LIB"],
                 "FDEE": ["FDEE"],
                 "ARAPV": ["ARAPV", "ARA, PV"],
                 "SOMVAL": ["SOMVAL"],
                 "PLD": ["PLD"],
                 "PFyV": ["PFyV"],
                 "PUM+J": ["PUM+J"],
                 "MÉS": ["MÉS"],
                 "EL PI": ["EL PI"],
                 "SAIn": ["SAIn"],
                 "CCD": ["CCD"],
                 "DN": ["DN"],
                 "EN POSITIU": ["EN POSITIU"],
                 "DL": ["DL"],
                 "mlgXSÍ": ["mlgXSÍ"],
                 "PCPC": ["PCPC"],
                 "EB": ["EB", "EB - AZ", "EB-AZ"],
                 "AVANT": ["AVANT"],
                 "SOLUCIONA": ["SOLUCIONA"],
                 "X ESQ": ["X ESQ"],
                 "PREPAL": ["PREPAL"],
                 "GBAI": ["GBAI"],
                 "CCa-PNC": ["CCa-PNC"],
                 "X LA IZQUIERDA-LOS VERDES": ["X LA IZQUIERDA-LOS VERDES"],
                 "PCOE": ["PCOE"],
                 "EU-eX": ["EU-eX"],
                 "IFem": ["IFem"],
                 "NÓS": ["NÓS"],
                 "PT": ["PT"],
                 "CILUS": ["CILUS"],
                 "AJU": ["AJU"],
                 "CRA": ["CRA"],
                 "EZKERRA": ["EZKERRA"],
                 "JS,PC": ["JS,PC"]}


grup_fus_prov = {'PSOE': ['PSE-EE (PSOE)', "PSOE", "PSE-EE", "PSdeG-PSOE", "PSC-PSOE", "PSOE-NCa"],
                 "PSC": ["PSC"],
                 "PODEMOS": ["PODEMOS-AHAL DUGU", "PODEMOS", "PODEMOS-Ahora Alto Aragón en Común"],
                 "EN COMÚ": ["EN COMÚ"],
                 "PODEMOS-COMPROMÍS": ["PODEMOS-COMPROMÍS", "PODEMOS - COMPROMIS"],
                 "PODEMOS-En Marea-ANOVA-EU": ["PODEMOS-En Marea-ANOVA-EU", "PODEMOS-EN MAREA-ANOVA-EU"],
                 'EH Bildu': ['EH Bildu'],
                 'UPYD': ['UPYD'],
                 "C's": ["C's", "C´s"],
                 "PP": ["PP-PAR", "PP", "PP-FORO", "UPN-PP"],
                 "EAJ-PNV": ["EAJ-PNV"],
                 "PACMA": ["PACMA"],
                 "IU": ["IU-UPeC", "UNIDAD POPULAR", "UPeC-IU-IZCA", "IU-UpeC", "IUC-UPeC", "IU-B-UPeC", "IU-CHA-UPeC", "UP-UPeC", "EUPV-UPeC", "UPeC-IU", "IULV-CA, UPeC", "IULV-CA,UPeC", "IU-UPeC-IAS", "UP: IULV-CA, UPeC", "UPB: IU-UPeC"],
                 "RECORTES CERO-GRUPO VERDE": ["RECORTES CERO-GRUPO VERDE"],
                 "CANARIAS DECIDE": ["CANARIAS DECIDE"],
                 "PCPE": ["PCPE"],
                 "Unió": ["Unio.Cat", "unio.cat"],
                 "VOX": ["VOX"],
                 "ERC": ["ERC-CATSI", "ERC-CATSÍ"],
                 "+MAS+": ["+MAS+"],
                 "Independientes-FIA": ["Independientes-FIA"],
                 "FE de las JONS": ["FE de las JONS"],
                 "PH": ["PH"],
                 "OE": ["OE"],
                 "Ln": ["Ln"],
                 "CENTRO MODERADO": ["CENTRO MODERADO"],
                 "P-LIB": ["P-LIB"],
                 "FDEE": ["FDEE"],
                 "ARAPV": ["ARAPV", "ARA, PV"],
                 "SOMVAL": ["SOMVAL"],
                 "PLD": ["PLD"],
                 "PFyV": ["PFyV"],
                 "PUM+J": ["PUM+J"],
                 "MÉS": ["MÉS"],
                 "EL PI": ["EL PI"],
                 "SAIn": ["SAIn"],
                 "CCD": ["CCD"],
                 "DN": ["DN"],
                 "EN POSITIU": ["EN POSITIU"],
                 "DL": ["DL"],
                 "mlgXSÍ": ["mlgXSÍ"],
                 "PCPC": ["PCPC"],
                 "EB": ["EB", "EB - AZ", "EB-AZ"],
                 "AVANT": ["AVANT"],
                 "SOLUCIONA": ["SOLUCIONA"],
                 "X ESQ": ["X ESQ"],
                 "PREPAL": ["PREPAL"],
                 "GBAI": ["GBAI"],
                 "CCa-PNC": ["CCa-PNC"],
                 "X LA IZQUIERDA-LOS VERDES": ["X LA IZQUIERDA-LOS VERDES"],
                 "PCOE": ["PCOE"],
                 "EU-eX": ["EU-eX"],
                 "IFem": ["IFem"],
                 "NÓS": ["NÓS"],
                 "PT": ["PT"],
                 "CILUS": ["CILUS"],
                 "AJU": ["AJU"],
                 "CRA": ["CRA"],
                 "EZKERRA": ["EZKERRA"],
                 "JS,PC": ["JS,PC"]}
